### ISSUE TITLE
Incorrectly links to pages not yet created

### ISSUE THREAD

**Issue by per-review** [bk/ikiwiki-plugin-wikiurl#1]
[See this comment](https://github.com/sciunto-org/ikiwiki-pandoc/issues/15#issuecomment-250683610).

**Comment by bk** [comment]
Fixed in commit ff9ffce.

**Comment by per-review** [comment]
First of all: I really appreciate your taking time to develop this plugin. Thank you! (Due to a busy week I couldn't have a look at it before now.)

I suspect that this bug hasn't been fixed yet. A normal wikilink to a non-existing page links to the path of the `cgiurl` (in the setup file), e.g. `/directory/ikiwiki.cgi?` etc. (excluding the domain). On the other hand, a wikiurl on a page two levels below the path of the `cgiurl` results in `../../directory/ikiwiki.cgi?` etc., i.e. to the relative path of the `cgiurl` directory *+ the path of the `cgiurl`. Maybe this only is a problem when the wiki url is not a subdirectory. (In case it matters, `url` and `cgiurl` point to the same directory in my setup.)

Again, I looked at the code, but I know to little to fix it myself.

**Comment by bk** [comment]
Thanks for your comments. I can see now that it would be best not to relativize links to the cgi script, including links to create non-existent pages, so I changed this as you requested.

In general, I think it would be a good idea to make it configurable whether absolute or relative paths are output for any link, as described in issue #3. (But I don't have time to implement this right now.)
